# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0
MAINTAINER DS

# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY ./target/hello-world-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/